# Generated by Django 3.2 on 2022-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=50)),
                ('description', models.TextField(default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
