# Generated by Django 3.2 on 2022-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
