# Generated by Django 3.2 on 2022-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_rename_created_by_todomodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
